import Head from 'next/head'
import { PageLayout } from '@/components/layout'
import { Main } from "@/components/Main/Main";
import { ThemeProvider } from "@/providers/ThemeProvider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next sandbox lifecycle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider>
        <PageLayout>
          <Main />
        </PageLayout>
      </ThemeProvider>
    </>
  )
}
