name: Deploy Next.js on VPS

on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint


  deploy:
    needs: lint
    runs-on: ubuntu-latest
#    concurrency:
#      group: lifecycle-sandbox
#      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          command: source ~/.nvm/nvm.sh; echo 'hello'
